// <auto-generated />

using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Blog.Main.Migrations
{
    public sealed partial class Initialization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initialization));
        
        string IMigrationMetadata.Id
        {
            get { return "201305091223280_Initialization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
